[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  ESLINT_NO_DEV_ERRORS = "true"
  NEXT_LINT_IGNORE_ESLINT = "true"
  NEXT_TYPESCRIPT_CHECK_DISABLED = "true"
  TYPESCRIPT_INCREMENTAL = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
