[build]
  command = "rm -rf node_modules package-lock.json .next && npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  ESLINT_NO_DEV_ERRORS = "true"
  NEXT_LINT_IGNORE_ESLINT = "true"
  NEXT_TYPESCRIPT_CHECK_DISABLED = "true"
  TYPESCRIPT_INCREMENTAL = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
